[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "treeparse"
version = "0.1.2.post1"
description = "Intuitive CLI framework using argparse, rich, and pydantic"
readme = "README.md"
authors = [{ name = "wr1" }]
requires-python = ">=3.8"
dependencies = [
    "rich>=13.3.1,<14",
    "pydantic>=2.0.2,<3",
]

[project.scripts]
demo = "examples.demo:main"
basic = "examples.basic:main"
list_demo = "examples.list_demo:main"
basic_super = "examples.basic_super:main"
choice_demo = "examples.choice_demo:main"
chain_demo = "examples.chain_demo:main"
group_option_demo = "examples.group_option_demo:main"
group_arg_demo = "examples.group_arg_demo:main"
theme_demo = "examples.theme_demo:main"

[dependency-groups]
dev = [
    "pytest~=7.0",
    "pytest-cov~=4.0",
    "ruff>=0.0.260,<0.0.261",
]



